### ISSUE TITLE
breaking changes to cloud.google.com/go/datastore

### ISSUE THREAD

**Issue by jba** [dataux/dataux#32]
See https://groups.google.com/forum/#!topic/google-api-go-announce/hqXtM_4Ix-0 and https://groups.google.com/forum/#!topic/google-api-go-announce/79jtrdeuJAg.

**Comment by araddon** [comment]
thx for the report

Fixed in https://github.com/dataux/dataux/pull/31/commits/f126b5d2f345b8bab6d73e79aaca765c8607062c
