### ISSUE TITLE
How way to make sql query to bson.M?

### ISSUE THREAD

**Issue by jacoblai** [dataux/dataux#49]
@araddon Hi ~! I need you help. In my project I want to make sql string to mgo bson.M {}, I can easy way to makesure it? thank a lot!

**Comment by araddon** [comment]
@jacoblai I don't have an easy way.  I have been working on a new pattern/interface for the  sql -> dialect translations.  Currently in https://github.com/dataux/dataux/blob/master/backends/mongo/sql_to_mgo.go#L74  the translation occurs to create the `bson.m{}` query, but it is relatively tightly coupled.   I plan on extracting that sql_to_mgo as a standalone **Generator** at some point.  Here is the rough process of converting


https://github.com/araddon/qlbridge/blob/master/exec/sqldriver.go#L206

1.  sql string to plan context
2.  job := planner(planctx)
3.  job(resultsWriter)


A question:  After you get a bson.M{} what do you want to do with the results?  ie what format of data?   IT would probably be relatively trivial for me to implement this mongo to be usble from go sql interface if that would work.

**Comment by jacoblai** [comment]
got it! thanks a lot for you!

**Comment by jacoblai** [comment]
got it! thanks a lot for you!
